from pathlib import Path

root = Path(__file__).resolve().parents[1]

# Patch the historical full generator before the orchestrator executes it.
full = root / "scripts/_agent_invite_completion_20260822.py"
if full.exists():
    text = full.read_text(encoding="utf-8")
    text = text.replace('admin_html = ROOT / "apps/admin/index.html"', 'admin_html = ROOT / "apps/admin/v12-operations.html"')
    full.write_text(text, encoding="utf-8")

# Patch the authoritative generator and its generated test bodies.
authoritative = root / "scripts/_agent_invite_authoritative_20260822.py"
if authoritative.exists():
    text = authoritative.read_text(encoding="utf-8")
    text = text.replace('ADMIN_HTML = ROOT / "apps/admin/index.html"', 'ADMIN_HTML = ROOT / "apps/admin/v12-operations.html"')
    text = text.replace('/apps/admin/index.html', '/apps/admin/v12-operations.html')
    authoritative.write_text(text, encoding="utf-8")

# If files were already generated by a previous attempt, correct them directly.
admin_html = root / "apps/admin/v12-operations.html"
if not admin_html.exists():
    raise RuntimeError("real admin entry apps/admin/v12-operations.html is missing")
html = admin_html.read_text(encoding="utf-8")
if "vendor/qrcode.min.js" not in html:
    marker = '<script src="./app.js"></script>'
    if marker not in html:
        marker = '<script src="app.js"></script>'
    if marker not in html:
        raise RuntimeError("real admin app script tag not found")
    html = html.replace(marker, '<script src="./vendor/qrcode.min.js"></script>\n  ' + marker, 1)
admin_html.write_text(html, encoding="utf-8")

front = root / "apps/api/tests/test_invite_frontend_contract.py"
if front.exists():
    text = front.read_text(encoding="utf-8")
    text = text.replace('ADMIN_HTML = ROOT / "apps/admin/index.html"', 'ADMIN_HTML = ROOT / "apps/admin/v12-operations.html"')
    front.write_text(text, encoding="utf-8")

browser = root / "apps/api/tests/test_invite_browser_smoke.py"
if browser.exists():
    text = browser.read_text(encoding="utf-8")
    text = text.replace('/apps/admin/index.html', '/apps/admin/v12-operations.html')
    browser.write_text(text, encoding="utf-8")

print("real admin entry patched")
